# Site settings
title: Sam's Trip to China
subtitle: Two years of college Chinese is enough, right?
description: >- # this means to ignore newlines until next item
  UT Austin Graduate.
  Out and about!
  This is just my travel blog; also see samm81.github.io
baseurl:
url: http://yourdomain.com

footer-links:
  email: samwmaynard@gmail.com
  twitter: samwmaynard
  github: samm81
  instagram:
  rss: hjkl # just type anything here for a working RSS icon

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
