# Site settings
title: Sam's Trip to China
subtitle: Two years of college Chinese is enough, right?
description: >- # this means to ignore newlines until next item
  UT Austin Graduate.
  Out and about!
  This is just my travel blog; also see samm81.github.io

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://samstriptochina.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:

footer-links:
  email: samwmaynard@gmail.com
  twitter: samwmaynard
  github: samm81
  instagram:
  rss: hjkl # just type anything here for a working RSS icon

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
  style: :compressed

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-104896580-2

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
